### ISSUE TITLE
BLAST Database error: No alias or index file found for nucleotide database [tmp_transcripts_with_orf.fa] in search path [/gpfs/scratch/ml0094::]

### ISSUE THREAD

**Issue by ml0094** [huangzixia/ExUTR#8]
Hello, so I've been trying to run this for several days. I am having an issue where it's failing to produce any tmp_blast files. Any file beginning with that prefix is blank. As a result it is failing when it gets to the above. I am using a modern unitprot database. Perl script has been edited and looks like this
[3UTR_orf_20170816.txt](https://github.com/huangzixia/ExUTR/files/8884523/3UTR_orf_20170816.txt)

This is using your test data set.
.

**Comment by ml0094** [comment]
Issue was resolved by changing the file in the run script to not refer to an extension for the swissprot fasta (directory/swissport v.s. directory/swissprot.fasta)

**Comment by r0ark** [comment]
Hi @ml0094 , did you upload your forked version of the script? I would like to be able to use a modern swissprot database to use this as well. Thanks in advance!

**Comment by ml0094** [comment]
> Hi @ml0094 , did you upload your forked version of the script? I would like to be able to use a modern swissprot database to use this as well. Thanks in advance!

I actually couldn't get the ORF prediction script to function on my data, so I resorted to manually following the steps instituted in the paper as I only had a very small number of genes of interest. I can look for my ORF prediction script but it was not funcitoning.
